name: LieRing
version: "2.4.2"
license: "GPL-2.0-or-later"
date: 2022-02-10
description: |
    Computing with finitely presented Lie rings

authors:
    - name: Serena Cicalò
      url: mailto:cicalo@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Serena Cicalò
      url: mailto:cicalo@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/liering/
readme: README.md
packageinfo: https://gap-packages.github.io/liering/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liering/releases/download/v2.4.2/liering-2.4.2.tar.gz

abstract: |
    The package <span class="pkgname">LieRing</span> contains                  functionality for working with finitely presented Lie rings and the Lazard correspondence.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Lie rings, Lazard correspondence.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CGT22</span>]   <b class='BibAuthor'>Cicalò, S., de Graaf, W. A. and GAP Team, T.</b>,
     <i class='BibTitle'>LieRing, Computing with finitely presented Lie rings,
             Version 2.4.2</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/liering/">https://gap-packages.github.io/liering/</a></span>.
    </p>
    

bibtex: |
    @misc{ LieRing2.4.2,
      author =           {Cical{\a`o}, S. and de Graaf, W. A. and GAP Team, T.},
      title =            {{LieRing},   Computing  with  finitely  presented  Lie
                          rings, {V}ersion 2.4.2},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/liering/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{liering/}}},
      keywords =         {Lie rings; Lazard correspondence},
      printedkey =       {CGT22}
    }

