name: LieRing
version: 2.3
date: 2016-11-01
description: |
    Computing with finitely presented Lie rings

authors:
    - name: Serena Cicalò
      url: mailto:cicalo@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Serena Cicalò
      url: mailto:cicalo@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

GAP: ">=4.8"

www: https://gap-packages.github.io/liering/
readme: README.md
packageinfo: https://gap-packages.github.io/liering/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liering/releases/download/v2.3/liering-2.3.tar.gz

abstract: |
    The package <span class="pkgname">LieRing</span> contains                  functionality for working with finitely presented Lie rings and the Lazard correspondence.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Lie rings, Lazard correspondence.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CG16</span>]   <b class='BibAuthor'>Cicalò, S. and de Graaf, W. A.</b>,
     <i class='BibTitle'>LieRing, Computing with finitely presented Lie rings,
             Version 2.3</i>
     (<span class='BibYear'>2016</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/liering/">https://gap-packages.github.io/liering/</a></span>.
    </p>
    

bibtex: |
    @misc{ LieRing2.3,
      author =           {Cical{\a`o}, S. and de Graaf, W. A.},
      title =            {{LieRing}, Computing with finitely presented Lie rings, {V}ersion 2.3},
      month =            {Nov},
      year =             {2016},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://gap-packages.github.io/liering/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{liering/}}},
      keywords =         {Lie rings; Lazard correspondence},
      printedkey =       {CG16}
    }

